worker_processes auto;
events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            record off;
            allow play all;
            allow publish all;

            # Подключаем все push-адреса из отдельной директории
            include /etc/nginx/rtmp-push/*.conf;
        }
    }
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;
}